/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author a1625381
 */
public class semLogin extends javax.swing.JPanel {

    /**
     * Creates new form semLogin
     */
    private mainFrame m;
    public void setMain(mainFrame mainframe)
    {
      this.m = mainframe;  
    }
    public semLogin() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarCadastroButton = new javax.swing.JButton();
        fazerLoginButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 0));

        criarCadastroButton.setText("Cadastrar");
        criarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarCadastroButtonActionPerformed(evt);
            }
        });
        add(criarCadastroButton);

        fazerLoginButton.setText("Fazer Login");
        fazerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerLoginButtonActionPerformed(evt);
            }
        });
        add(fazerLoginButton);
    }// </editor-fold>//GEN-END:initComponents

    private void criarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarCadastroButtonActionPerformed
        CadastrarUsuarioFrame panel = new CadastrarUsuarioFrame();
        panel.setVisible(true);
    }//GEN-LAST:event_criarCadastroButtonActionPerformed

    private void fazerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerLoginButtonActionPerformed
        loginFrame panel = new loginFrame();
        panel.setMain(m);
        panel.setVisible(true);
    }//GEN-LAST:event_fazerLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarCadastroButton;
    private javax.swing.JButton fazerLoginButton;
    // End of variables declaration//GEN-END:variables
}
